### ISSUE TITLE
support for non bbox roi in sampler

### ISSUE THREAD

**Issue by asaph-marvin** [microsoft/torchgeo#1190]
### Summary

Add option to pass Polygon, MultiPolygon or oriented bounding box as the roi param to the geosampler. (and perhaps support other geometry types?)
The sampler would then sample bounding boxes that have their center fall somewhere inside the polygon / multipolygon, or in the case of the oriented bounding box, it would sample from patches from the OBB and use the rotation matrix to sample the actual image data.

### Rationale

I'm using a global coastal dataset. It is therefor made up of very narrow strips, oriented in many directions spread out over the entire globe. The minimum bounding box for this dataset is basically the whole world, but the actual coast line makes up a tiny fragment of that bounding box. So the chance that the geo sampler will sample a "valid" image for me is basically 0. 

ATM I have to manually split up my dataset many small bounding boxes and create a dataloader for each one. This is labour intensive and suboptimal because there isn't one clear way to cut the coastal region up into bboxes.

Instead it would be very convenient if I could simply pass the multi polygon to the geo sampler. I don't mind if the sampled images will have some pixels outside the roi as long as the center of the image is contained inside the roi.

### Implementation

use the bounding boxes of the polygons / oriented bounding box to sample points and then perform isContained() test for the points to see if they fall within the polygons / oriented bounding box

**Comment by adamjstewart** [comment]
@calebrob6 had some working code for this.

**Comment by calebrob6** [comment]
Looking back at issues assigned to me -- this wouldn't be hard to hack, but I'm not sure the _proper_ way to implement it. Our `BoundingBox` has temporal dimensions too, so we'd need some `BoundingShape` wrapper around shapely Polygon | MultiPolygon that appended a temporal dimension and worked with BoundingBox.

**Comment by adamjstewart** [comment]
This is finally happening in #2812!

**Comment by mauropk** [comment]
Hi, i am using torchgeo==0.7.1 but GeoSampler still expects a BoundingBox as roi. Is this feature going to be introduced with future releases or i could be doing something wrong? This is the error i get: 

```
Traceback (most recent call last):
  File "C:\Users\pavanello\Documents\repos\P22G2265_IRIDE_SVC_S4_02\dev\playground\datacube_experiments\torchgeo_approach_v1\dem_plus_planet_ss_mask_sampling_test.py", line 149, in <module>
    sampler = RandomGeoSampler(training_ds, size=PATCH_SIZE, length=None, roi=aoi_polygon)
  File "C:\ProgramData\miniforge3\envs\pk_seg_env\Lib\site-packages\torchgeo\samplers\single.py", line 109, in __init__
    super().__init__(dataset, roi)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\ProgramData\miniforge3\envs\pk_seg_env\Lib\site-packages\torchgeo\samplers\single.py", line 42, in __init__
    hits = dataset.index.intersection(tuple(roi), objects=True)
                                      ~~~~~^^^^^
TypeError: 'Polygon' object is not iterable
```

**Comment by isaaccorley** [comment]
@mauropk yes this feature will be in the next major release. You can install from the main branch if you would like to test it out today though.
