### ISSUE TITLE
RandomBatchGeoSampler produces nan or nodata values

### ISSUE THREAD

**Issue by tgoelles** [microsoft/torchgeo#2029]
### Description

I have a shapefile and the geotiff file with 3 bands. The geotiff and shapefile cover the same ROI and has no nan values. When I combine the two datasets and use a RandomBatchGeoSampler I get empty tensors form the geotiff.
[05_model_input.zip](https://github.com/microsoft/torchgeo/files/15127623/05_model_input.zip)

It already took quite some time to narrow down the issue. Some build in checks for nan or inf would be nice.

### Steps to reproduce

1.) copy the data and extract it form the zip file given above.
2.) run this code:

```python

from torchgeo.samplers import RandomBatchGeoSampler, RandomGeoSampler

from torchgeo.datasets import RasterDataset, VectorDataset
from torchgeo.datasets.utils import BoundingBox
import torch
from typing import Any
import os
import rioxarray
import geopandas as gpd

geotiff_path = "pre_processed_multiband.tif"
shapefile_path = "avalanche_outline_model_input.shp"

class MasterDataset(RasterDataset):
    filename_glob = "pre_processed*.tif"
    filename_regex = r"pre_processed_(.*?)\.tif"
    all_bands = ["vh", "vv", "vvvh"]
    separate_files = False
    is_image = True

    def __init__(self, root: str, **kwargs: Any):
        super().__init__(root, **kwargs)

    def __getitem__(self, query: BoundingBox) -> dict[str, Any]:
        sample = super().__getitem__(query)
        return sample

class AvalancheMasksDataset(VectorDataset):
    filename_glob = "aval_outlines*.shp"
    separate_files = False
    is_image = False

    def __init__(self, root: str, **kwargs: Any):
        super().__init__(root, **kwargs)

    def __getitem__(self, query: BoundingBox) -> dict[str, Any]:
        sample = super().__getitem__(query)
        return sample

current_dir = os.getcwd()

master_dataset = MasterDataset(current_dir)
avalanche_masks_dataset = AvalancheMasksDataset(current_dir + "/avalanche_outline_model_input.shp")

dataset = master_dataset & avalanche_masks_dataset

size = 20
sampler = RandomBatchGeoSampler(dataset, size, batch_size=1, length=1)

for batch_index, batch in enumerate(sampler):
    for query_index, query in enumerate(batch):
        print(f"Batch {batch_index}, Query {query}")
        sample = dataset[query]

        # Count NaN and non-NaN values for image
        nan_count_image = torch.isnan(sample["image"]).sum().item()
        non_nan_count_image = torch.numel(sample["image"]) - nan_count_image
        nodata_count_image = (sample["image"] == -9999).sum().item()

        if nan_count_image > 0 or nodata_count_image > 0:
            print(
                f"NaN values found in image with shape {sample['image'].shape}. "
                f"NaN count: {nan_count_image}, Non-NaN count: {non_nan_count_image}, NoData count (-9999): {nodata_count_image}")

```

3.) The rusult is: 
Batch 0, Query BoundingBox(minx=558197.8752828322, maxx=558597.8752828322, miny=5182815.3526341915, maxy=5183215.3526341915, mint=0.0, maxt=9.223372036854776e+18)
NaN values found in image with shape torch.Size([3, 20, 20]). NaN count: 0, Non-NaN count: 1200, NoData count (-9999): 1200

Which indicates that all values in the image are NoData values.

### Version

0.5.2

**Comment by adamjstewart** [comment]
Hi @tgoelles! Congrats on your paper: https://doi.org/10.3389/frsen.2023.1156519. Our lab was recently in Austria for our winter school and I mentioned your group as one of our TorchGeo users.

**Comment by adamjstewart** [comment]
I was able to reproduce this issue without using any sampler:
```python
import rasterio
from torchgeo.datasets import BoundingBox, RasterDataset

path = "data/05_model_input/pre_processed_multiband.tif"

# Original data does not contain NaNs
f = rasterio.open(path)
ar = f.read()
print(ar)
print("NaNs:", (ar == f.nodata).sum())

# But it does when read by TorchGeo
ds = RasterDataset(path)
query = BoundingBox(558648, 559048, 5184009, 5184409, 0, 1e19)
sample = ds[query]
image = sample["image"]
print(image)
print("NaNs:", (image == f.nodata).sum().item())
```
Still investigating...

**Comment by adamjstewart** [comment]
I suspect that there is something wrong with the file itself. TorchGeo just uses `rasterio.merge.merge` to read the file. When I try to open the file without using TorchGeo:
```python
import rasterio.merge

path = "data/05_model_input/pre_processed_multiband.tif"
rasterio.merge.merge([path])
```
I encounter the following error:
```
Traceback (most recent call last):
  File "/Users/Adam/torchgeo/test2.py", line 4, in <module>
    rasterio.merge.merge([path])
  File "/Users/Adam/spack/var/spack/environments/default/.spack-env/view/lib/python3.11/site-packages/rasterio/merge.py", line 344, in merge
    dst_window = windows.from_bounds(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Adam/spack/var/spack/environments/default/.spack-env/view/lib/python3.11/site-packages/rasterio/windows.py", line 324, in from_bounds
    raise WindowError("Bounds and transform are inconsistent")
rasterio.errors.WindowError: Bounds and transform are inconsistent
```
How was the file created?

**Comment by tgoelles** [comment]
Hi, 

> Hi @tgoelles! Congrats on your paper: https://doi.org/10.3389/frsen.2023.1156519. Our lab was recently in Austria for our winter school and I mentioned your group as one of our TorchGeo users.

Thanks! Also for your quick answer.

Here is how the geotiff is generated. Its generated with rioxarray:

```python
def export_to_multiband_geotiff(master_dataset: xarray.Dataset, paramters: dict) -> str:
    model_input_path = Path("/workspaces/avalanche/project/data/05_model_input")
    save_path = model_input_path / f"pre_processed_multiband.tif"

    bands_stack = xarray.concat([master_dataset["vv"], master_dataset["vh"], master_dataset["vvvh"]], dim="band")
    bands_stack = bands_stack.assign_coords(band=("band", ["vv", "vh", "vvvh"]))

    LOG.info(f"Saving multiband data to {save_path}")
    bands_stack = bands_stack.rio.write_crs(master_dataset.rio.crs)

    nodata_value = paramters["master_options"]["geotiff_nodata"]
    LOG.info(f"Setting nodata value to {nodata_value}")
    bands_stack.rio.write_nodata(nodata_value, inplace=True)
    bands_stack.rio.to_raster(save_path)

    return save_path.as_posix()

**Comment by adamjstewart** [comment]
Could possibly be a bug in rioxarray. Might be worth reporting to them or to rasterio to see where the issue is. It doesn't seem to be a bug in TorchGeo though.

**Comment by tgoelles** [comment]
Ok, thanks a lot. When I read it with rioxarray or in QGIS or rastervision it works. I need to investigate this further. This should now make it possible for me to solve this and you can close the issue.
