### ISSUE TITLE
Seg Fault when importing datasets

### ISSUE THREAD

**Issue by bhaktatejas922** [microsoft/torchgeo#271]
`Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torch.utils.data import DataLoader
>>> from torchgeo.datasets import LandCoverAI, Potsdam2D, Vaihingen2D, stack_samples
[1]    15647 segmentation fault (core dumped)  python3
`

**Comment by bhaktatejas922** [comment]
Tried in a fresh environment, no more seg fault, but: 

`Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from torchgeo.datasets import LandCoverAI, Potsdam2D, Vaihingen2D, stack_samples
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tbhakta/anaconda3/envs/cartographer/lib/python3.6/site-packages/torchgeo/__init__.py", line 16, in <module>
    from .datasets import (
  File "/home/tbhakta/anaconda3/envs/cartographer/lib/python3.6/site-packages/torchgeo/datasets/__init__.py", line 6, in <module>
    from .advance import ADVANCE
  File "/home/tbhakta/anaconda3/envs/cartographer/lib/python3.6/site-packages/torchgeo/datasets/advance.py", line 15, in <module>
    from .geo import VisionDataset
  File "/home/tbhakta/anaconda3/envs/cartographer/lib/python3.6/site-packages/torchgeo/datasets/geo.py", line 33, in <module>
    from .utils import BoundingBox, concat_samples, disambiguate_timestamp, merge_samples
  File "/home/tbhakta/anaconda3/envs/cartographer/lib/python3.6/site-packages/torchgeo/datasets/utils.py", line 37, in <module>
    from torchvision.utils import draw_segmentation_masks
ImportError: cannot import name 'draw_segmentation_masks'

>>> import torchvision
>>> torchvision.__version__
'0.9.0a0'
`

**Comment by adamjstewart** [comment]
Thanks for reporting this! The former issue looks like a conda issue. The latter issue is an actual bug though. We need to update our minimum required version of torchvision. If you install torchvision 0.10 or newer it should work.

**Comment by calebrob6** [comment]
(Thanks for the issue @bhaktatejas922!) We just bumped the minimum required torchvision dependency to account for this.

Do you mind trying again? (e.g. following https://torchgeo.readthedocs.io/en/latest/user/installation.html#id2):
```
git clone https://github.com/microsoft/torchgeo.git
cd torchgeo
conda env create --file environment.yml
conda activate torchgeo
pip install .
```

**Comment by adamjstewart** [comment]
Note that the PR hasn't been merged yet
