### ISSUE TITLE
IndexError with dtype conversion in prepare_data() or RunTimeError without

### ISSUE THREAD

**Issue by KennSmithDS** [microsoft/torchgeo#303]
**Description of Issue**
As per recommendations by @calebrob6 and @isaaccorley in [#302](https://github.com/microsoft/torchgeo/issues/302), I have changed the Sentinel2CloudCover Dataset to extend the VisionDataset instead of Sentinel2, and refactored both the constructor and `__getitem__()` methods to build a string path of chip ids by walking root directory, and then getting the paired `image` (float32) and `mask` (int) GeoTiffs when building each item dict. It appears to be loading the data if I don't have any conversion to Tensor but eventually snags a RuntimeError when calculating the Jaccard loss. However, if I do try to convert ndarray to Tensor first as `one_hot` requires, it throws an IndexError when loading the items. Uncertain how to change the `custom_transform()` method to avert these two issues.

Please reference code [here](https://github.com/KennSmithDS/drivendata_cloud_competition/blob/2d0da9c92b80c1eefb40ddfa7625c164a42a2c7e/cloud.py#L97):

I used these three DataModule types as reference from torchgeo source code:
- `chesapeake.py` converts `image` to `float()` and `mask` to `long()`
- `so2sat.py` converts `image` to `float()`
- cyclone.py` converts `image` to scale of [0, 1] and `label` to Tensor

**First Error: Converting ndarray to Tensor in custom_transform() call**
```
Traceback (most recent call last):
  File "/home/ying/cloud_cover_competition/cloud.py", line 111, in __getitem__
    "image": self._load_feature(chip),
  File "/home/ying/cloud_cover_competition/cloud.py", line 111, in __getitem__
    "image": self._load_feature(chip),
  File "/home/ying/cloud_cover_competition/cloud.py", line 141, in _load_feature
    x_arr = self.transforms(x_arr)
  File "/home/ying/cloud_cover_competition/cloud.py", line 198, in custom_transform
    sample["image"] = torch.from_numpy(sample["image"])
  File "/home/ying/cloud_cover_competition/cloud.py", line 141, in _load_feature
    x_arr = self.transforms(x_arr)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
  File "/home/ying/cloud_cover_competition/cloud.py", line 198, in custom_transform
    sample["image"] = torch.from_numpy(sample["image"])
------------------------------------------------------------
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

![CloudCoverDataModule_RuntimeError](https://user-images.githubusercontent.com/30271891/146654390-6c90c178-063c-4888-b972-d9e6b72a5fd6.png)

**Second Error: Without conversion to Tensor in custom_transform() call**
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_82513/4274221884.py in <module>
----> 1 lightning_trainer.fit(model=semseg_task, datamodule=cloud_module)

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in fit(self, model, train_dataloaders, val_dataloaders, datamodule, train_dataloader, ckpt_path)
    735             )
    736             train_dataloaders = train_dataloader
--> 737         self._call_and_handle_interrupt(
    738             self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    739         )

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    680         """
    681         try:
--> 682             return trainer_fn(*args, **kwargs)
    683         # TODO: treat KeyboardInterrupt as BaseException (delete the code below) in v1.7
    684         except KeyboardInterrupt as exception:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    770         # TODO: ckpt_path only in v1.7
    771         ckpt_path = ckpt_path or self.resume_from_checkpoint
--> 772         self._run(model, ckpt_path=ckpt_path)
    773 
    774         assert self.state.stopped

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _run(self, model, ckpt_path)
   1192 
   1193         # dispatch `start_training` or `start_evaluating` or `start_predicting`
-> 1194         self._dispatch()
   1195 
   1196         # plugin will finalized fitting (e.g. ddp_spawn will load trained model)

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _dispatch(self)
   1272             self.training_type_plugin.start_predicting(self)
   1273         else:
-> 1274             self.training_type_plugin.start_training(self)
   1275 
   1276     def run_stage(self):

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in start_training(self, trainer)
    200     def start_training(self, trainer: "pl.Trainer") -> None:
    201         # double dispatch to initiate the training loop
--> 202         self._results = trainer.run_stage()
    203 
    204     def start_evaluating(self, trainer: "pl.Trainer") -> None:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in run_stage(self)
   1282         if self.predicting:
   1283             return self._run_predict()
-> 1284         return self._run_train()
   1285 
   1286     def _pre_training_routine(self):

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py in _run_train(self)
   1312         self.fit_loop.trainer = self
   1313         with torch.autograd.set_detect_anomaly(self._detect_anomaly):
-> 1314             self.fit_loop.run()
   1315 
   1316     def _run_evaluate(self) -> _EVALUATE_OUTPUT:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    143             try:
    144                 self.on_advance_start(*args, **kwargs)
--> 145                 self.advance(*args, **kwargs)
    146                 self.on_advance_end()
    147                 self.restarting = False

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py in advance(self)
    232 
    233         with self.trainer.profiler.profile("run_training_epoch"):
--> 234             self.epoch_loop.run(data_fetcher)
    235 
    236             # the global step is manually decreased here due to backwards compatibility with existing loggers

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    143             try:
    144                 self.on_advance_start(*args, **kwargs)
--> 145                 self.advance(*args, **kwargs)
    146                 self.on_advance_end()
    147                 self.restarting = False

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py in advance(self, *args, **kwargs)
    191 
    192             with self.trainer.profiler.profile("run_training_batch"):
--> 193                 batch_output = self.batch_loop.run(batch, batch_idx)
    194 
    195         self.batch_progress.increment_processed()

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    143             try:
    144                 self.on_advance_start(*args, **kwargs)
--> 145                 self.advance(*args, **kwargs)
    146                 self.on_advance_end()
    147                 self.restarting = False

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py in advance(self, batch, batch_idx)
     86         if self.trainer.lightning_module.automatic_optimization:
     87             optimizers = _get_active_optimizers(self.trainer.optimizers, self.trainer.optimizer_frequencies, batch_idx)
---> 88             outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
     89         else:
     90             outputs = self.manual_loop.run(split_batch, batch_idx)

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/base.py in run(self, *args, **kwargs)
    143             try:
    144                 self.on_advance_start(*args, **kwargs)
--> 145                 self.advance(*args, **kwargs)
    146                 self.on_advance_end()
    147                 self.restarting = False

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in advance(self, batch, *args, **kwargs)
    213 
    214     def advance(self, batch: Any, *args: Any, **kwargs: Any) -> None:  # type: ignore[override]
--> 215         result = self._run_optimization(
    216             batch,
    217             self._batch_idx,

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in _run_optimization(self, split_batch, batch_idx, optimizer, opt_idx)
    264         # gradient update with accumulated gradients
    265         else:
--> 266             self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
    267 
    268         result = closure.consume_result()

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in _optimizer_step(self, optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
    376 
    377         # model hook
--> 378         lightning_module.optimizer_step(
    379             self.trainer.current_epoch,
    380             batch_idx,

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py in optimizer_step(self, epoch, batch_idx, optimizer, optimizer_idx, optimizer_closure, on_tpu, using_native_amp, using_lbfgs)
   1650 
   1651         """
-> 1652         optimizer.step(closure=optimizer_closure)
   1653 
   1654     def optimizer_zero_grad(self, epoch: int, batch_idx: int, optimizer: Optimizer, optimizer_idx: int):

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py in step(self, closure, **kwargs)
    162         assert trainer is not None
    163         with trainer.profiler.profile(profiler_action):
--> 164             trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py in optimizer_step(self, optimizer, opt_idx, closure, model, **kwargs)
    334         """
    335         model = model or self.lightning_module
--> 336         self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
    337 
    338     def optimizer_zero_grad(self, current_epoch: int, batch_idx: int, optimizer: Optimizer, opt_idx: int) -> None:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py in optimizer_step(self, model, optimizer, optimizer_idx, closure, **kwargs)
    161         if isinstance(model, pl.LightningModule):
    162             closure = partial(self._wrap_closure, model, optimizer, optimizer_idx, closure)
--> 163         optimizer.step(closure=closure, **kwargs)
    164 
    165     def _track_grad_norm(self, trainer: "pl.Trainer") -> None:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/torch/optim/optimizer.py in wrapper(*args, **kwargs)
     86                 profile_name = "Optimizer.step#{}.step".format(obj.__class__.__name__)
     87                 with torch.autograd.profiler.record_function(profile_name):
---> 88                     return func(*args, **kwargs)
     89             return wrapper
     90 

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     26         def decorate_context(*args, **kwargs):
     27             with self.__class__():
---> 28                 return func(*args, **kwargs)
     29         return cast(F, decorate_context)
     30 

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/torch/optim/adam.py in step(self, closure)
     90         if closure is not None:
     91             with torch.enable_grad():
---> 92                 loss = closure()
     93 
     94         for group in self.param_groups:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py in _wrap_closure(self, model, optimizer, optimizer_idx, closure)
    146         consistent with the ``PrecisionPlugin`` subclasses that cannot pass ``optimizer.step(closure)`` directly.
    147         """
--> 148         closure_result = closure()
    149         self._after_closure(model, optimizer, optimizer_idx)
    150         return closure_result

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in __call__(self, *args, **kwargs)
    158 
    159     def __call__(self, *args: Any, **kwargs: Any) -> Optional[Tensor]:
--> 160         self._result = self.closure(*args, **kwargs)
    161         return self._result.loss
    162 

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in closure(self, *args, **kwargs)
    140     def closure(self, *args: Any, **kwargs: Any) -> ClosureResult:
    141         with self._profiler.profile("training_step_and_backward"):
--> 142             step_output = self._step_fn()
    143 
    144             if step_output.closure_loss is None:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py in _training_step(self, split_batch, batch_idx, opt_idx)
    433             lightning_module._current_fx_name = "training_step"
    434             with self.trainer.profiler.profile("training_step"):
--> 435                 training_step_output = self.trainer.accelerator.training_step(step_kwargs)
    436                 self.trainer.training_type_plugin.post_training_step()
    437 

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py in training_step(self, step_kwargs)
    214         """
    215         with self.precision_plugin.train_step_context():
--> 216             return self.training_type_plugin.training_step(*step_kwargs.values())
    217 
    218     def post_training_step(self) -> None:

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py in training_step(self, *args, **kwargs)
    211 
    212     def training_step(self, *args, **kwargs):
--> 213         return self.model.training_step(*args, **kwargs)
    214 
    215     def post_training_step(self):

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/torchgeo/trainers/segmentation.py in training_step(self, batch, batch_idx)
    134         y_hat_hard = y_hat.argmax(dim=1)
    135 
--> 136         loss = self.loss(y_hat, y)
    137 
    138         # by default, the train step logs every `log_every_n_steps` steps where

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1100         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102             return forward_call(*input, **kwargs)
   1103         # Do not call functions when jit is used
   1104         full_backward_hooks, non_full_backward_hooks = [], []

~/anaconda3/envs/torchgeo/lib/python3.9/site-packages/segmentation_models_pytorch/losses/jaccard.py in forward(self, y_pred, y_true)
     79             y_pred = y_pred.view(bs, num_classes, -1)
     80 
---> 81             y_true = F.one_hot(y_true, num_classes)  # N,H*W -> N,H*W, C
     82             y_true = y_true.permute(0, 2, 1)  # H, C, H*W
     83 

RuntimeError: one_hot is only applicable to index tensor.
```

**Comment by isaaccorley** [comment]
The transforms operate on a sample dict and should occur inside getitem. Your script has it ocurring inside _load_features and separately in _load_label on numpy arrays.

**Comment by KennSmithDS** [comment]
To clarify, if I return x_arr and y_arr without the transform logic, and move that into `__getitem__()` the problem will go away. Is this for the scenario with or without the tensor conversion? What data structure/type is the model expecting?

**Comment by isaaccorley** [comment]
You are doing everything else properly and should convert the arrays to tensors in _load_features and _load_labels. You just need to move the transform call into the getitem like:


sample = {"image": image, ...}
if self.transforms is not None:
   sample = self.transforms(sample)

return sample

**Comment by isaaccorley** [comment]
Can you provide the entire trace of the message? You shouldn't need to one_hot your mask. It should just be an int mask with pixel values that represent the classes.

**Comment by KennSmithDS** [comment]
The updated __getitem__() code is here:
- https://github.com/KennSmithDS/drivendata_cloud_competition/blob/ae0749cb667fadbc86ff7cda948a0fac564388f8/cloud.py#L116

The full traceback message can be seen above in the issue description, as well as in Cell #20 of this notebook:
- https://github.com/KennSmithDS/drivendata_cloud_competition/blob/main/cloud_cover_model.ipynb

**Comment by adamjstewart** [comment]
As far as I can tell, this is an issue with user code, not with the TorchGeo library. We're happy to debug issues with the TorchGeo library, or answer questions about things that are ambiguous in the documentation, but we don't yet have the resources to debug user code. StackOverflow might be a better place for this kind of question.

**Comment by calebrob6** [comment]
Hey @KennSmithDS,

Just downloaded the dataset and had a look at your repo. The only change I needed to make to get it working was add:
```
sample["image"] = sample["image"].float()
sample["mask"] = sample["mask"].long()
```
to the `custom_transform()` method.

This was a pretty sneaky bug. Apparently the jaccard loss from segmentation_models_pytorch needs to masks to be "torch.long" instead of "torch.int32".

**Comment by KennSmithDS** [comment]
Hey @calebrob6,

Appreciate you taking a look at this. Funny that it was such a simple fix to the bug, sneaky indeed. I didn't try to set it to long, as per @isaaccorley advice in #302 that the mask needed to be an int32, not long.

I've got the model training on my end now too! Next up, I'll integrate the dataset downloader component once we have it live on the MLHub API. 

Cheers!

**Comment by isaaccorley** [comment]
That's my fault. We normally convert masks to torch.long. Bot sure why I said int32.

**Comment by KennSmithDS** [comment]
No worries Isaac, I should have taken a closer look at PyTorch
documentation.

Also, the Chesapeake DataModule sets the "mask" to a `.long()` so it
wouldn't have hurt to try it when I saw that.
