### ISSUE TITLE
Cannot import TropicalCycloneDataModule' from 'torchgeo.datamodules'

### ISSUE THREAD

**Issue by FlorisCalkoen** [microsoft/torchgeo#888]
### Description

I'm trying to follow the [trainer tutorial](https://torchgeo.readthedocs.io/en/latest/tutorials/trainers.html), but I can't import the required datamodule. 

I'm creating a torchgeo environment using (see output below): 

` mamba create -n torchgeo python pip 'torchgeo[datasets]' -c conda-forge`

```
❯ mamba activate torchgeo
❯ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchgeo
>>> torchgeo.__version__
'0.3.1'
>>> from torchgeo.datamodules import TropicalCycloneDataModule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TropicalCycloneDataModule' from 'torchgeo.datamodules' (/Users/calkoen/miniconda3/envs/torchgeo/lib/python3.10/site-packages/torchgeo/datamodules/__init__.py)
```

Output from conda install: 

```
                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.25.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['python', 'pip', 'torchgeo']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/osx-arm64                                         Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/osx-arm64                                            Using cache
pkgs/r/noarch                                               Using cache
Transaction

  Prefix: /Users/calkoen/miniconda3/envs/torchgeo

  Updating specs:

   - python
   - pip
   - torchgeo


  Package                             Version  Build                 Channel                     Size
───────────────────────────────────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────────────────────────────────

  + absl-py                             1.3.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + affine                              2.3.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + aiohttp                             3.8.3  py310h8e9501a_1       conda-forge/osx-arm64     Cached
  + aiosignal                           1.2.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + antlr-python-runtime                4.9.3  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + async-timeout                       4.0.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + attrs                              22.1.0  pyh71513ae_1          conda-forge/noarch        Cached
  + blinker                               1.5  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + blosc                              1.21.1  hd414afc_3            conda-forge/osx-arm64     Cached
  + boost-cpp                          1.78.0  h1cb353e_1            conda-forge/osx-arm64     Cached
  + brotli                              1.0.9  h1a8c8d9_8            conda-forge/osx-arm64     Cached
  + brotli-bin                          1.0.9  h1a8c8d9_8            conda-forge/osx-arm64     Cached
  + brotlipy                            0.7.0  py310h8e9501a_1005    conda-forge/osx-arm64     Cached
  + bzip2                               1.0.8  h3422bc3_4            conda-forge/osx-arm64     Cached
  + c-ares                             1.18.1  h3422bc3_0            conda-forge/osx-arm64     Cached
  + ca-certificates                 2022.9.24  h4653dfc_0            conda-forge/osx-arm64     Cached
  + cachetools                          4.2.4  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + cairo                              1.16.0  h73a0509_1014         conda-forge/osx-arm64     Cached
  + certifi                         2022.9.24  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + cffi                               1.15.1  py310h2399d43_2       conda-forge/osx-arm64     Cached
  + cfitsio                             4.1.0  hd4f5c17_0            conda-forge/osx-arm64     Cached
  + charset-normalizer                  2.1.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + click                               8.1.3  unix_pyhd8ed1ab_2     conda-forge/noarch        Cached
  + click-plugins                       1.1.1  py_0                  conda-forge/noarch        Cached
  + cligj                               0.7.2  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + colorama                            0.4.6  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + contourpy                           1.0.6  py310h2887b22_0       conda-forge/osx-arm64     Cached
  + cryptography                       38.0.3  py310hfc83b78_0       conda-forge/osx-arm64     Cached
  + curl                               7.86.0  h1c293e1_1            conda-forge/osx-arm64     Cached
  + cycler                             0.11.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + efficientnet-pytorch                0.7.1  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + einops                              0.4.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + expat                               2.5.0  hb7217d7_0            conda-forge/osx-arm64     Cached
  + fiona                              1.8.22  py310hcdcf461_1       conda-forge/osx-arm64     Cached
  + font-ttf-dejavu-sans-mono            2.37  hab24e00_0            conda-forge/noarch        Cached
  + font-ttf-inconsolata                3.000  h77eed37_0            conda-forge/noarch        Cached
  + font-ttf-source-code-pro            2.038  h77eed37_0            conda-forge/noarch        Cached
  + font-ttf-ubuntu                      0.83  hab24e00_0            conda-forge/noarch        Cached
  + fontconfig                         2.14.1  h82840c6_0            conda-forge/osx-arm64     Cached
  + fonts-conda-ecosystem                   1  0                     conda-forge/noarch        Cached
  + fonts-conda-forge                       1  0                     conda-forge/noarch        Cached
  + fonttools                          4.38.0  py310h8e9501a_1       conda-forge/osx-arm64     Cached
  + freetype                           2.12.1  hd633e50_0            conda-forge/osx-arm64     Cached
  + freexl                              1.0.6  h1a8c8d9_1            conda-forge/osx-arm64     Cached
  + frozenlist                          1.3.1  py310h8e9501a_1       conda-forge/osx-arm64     Cached
  + fsspec                          2022.10.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + future                             0.18.2  pyhd8ed1ab_6          conda-forge/noarch        Cached
  + gdal                                3.5.3  py310h0b34360_1       conda-forge/osx-arm64     Cached
  + geos                               3.11.0  h9a09cb3_0            conda-forge/osx-arm64     Cached
  + geotiff                             1.7.1  h90559a4_4            conda-forge/osx-arm64     Cached
  + gettext                            0.21.1  h0186832_0            conda-forge/osx-arm64     Cached
  + giflib                              5.2.1  h27ca646_2            conda-forge/osx-arm64     Cached
  + google-auth                        1.35.0  pyh6c4a22f_0          conda-forge/noarch        Cached
  + google-auth-oauthlib                0.4.6  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + grpcio                             1.49.1  py310h8d8cf04_1       conda-forge/osx-arm64     Cached
  + hdf4                               4.2.15  h1a38d6a_5            conda-forge/osx-arm64     Cached
  + hdf5                               1.12.2  nompi_h33dac16_100    conda-forge/osx-arm64     Cached
  + icu                                  70.1  h6b3803e_0            conda-forge/osx-arm64     Cached
  + idna                                  3.4  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + importlib-metadata                  5.0.0  pyha770c72_1          conda-forge/noarch        Cached
  + joblib                              1.2.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + jpeg                                   9e  he4db4b2_2            conda-forge/osx-arm64     Cached
  + json-c                               0.16  hc449e50_0            conda-forge/osx-arm64     Cached
  + kealib                             1.4.15  h02ce806_1            conda-forge/osx-arm64     Cached
  + kiwisolver                          1.4.4  py310h2887b22_1       conda-forge/osx-arm64     Cached
  + kornia                              0.6.8  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + krb5                               1.19.3  he492e65_0            conda-forge/osx-arm64     Cached
  + lcms2                                2.14  h8193b64_0            conda-forge/osx-arm64     Cached
  + lerc                                4.0.0  h9a09cb3_0            conda-forge/osx-arm64     Cached
  + libabseil                      20220623.0  cxx17_h28b99d4_5      conda-forge/osx-arm64     Cached
  + libblas                             3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libbrotlicommon                     1.0.9  h1a8c8d9_8            conda-forge/osx-arm64     Cached
  + libbrotlidec                        1.0.9  h1a8c8d9_8            conda-forge/osx-arm64     Cached
  + libbrotlienc                        1.0.9  h1a8c8d9_8            conda-forge/osx-arm64     Cached
  + libcblas                            3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libcurl                            7.86.0  h1c293e1_1            conda-forge/osx-arm64     Cached
  + libcxx                             14.0.6  h2692d47_0            conda-forge/osx-arm64     Cached
  + libdap4                            3.20.6  h8510809_2            conda-forge/osx-arm64     Cached
  + libdeflate                           1.14  h1a8c8d9_0            conda-forge/osx-arm64     Cached
  + libedit                      3.1.20191231  hc8eb9b7_2            conda-forge/osx-arm64     Cached
  + libev                                4.33  h642e427_1            conda-forge/osx-arm64     Cached
  + libffi                              3.4.2  h3422bc3_5            conda-forge/osx-arm64     Cached
  + libgdal                             3.5.3  h6036c7f_1            conda-forge/osx-arm64     Cached
  + libgfortran                         5.0.0  11_3_0_hd922786_25    conda-forge/osx-arm64     Cached
  + libgfortran5                       11.3.0  hdaf2cc0_25           conda-forge/osx-arm64     Cached
  + libglib                            2.74.1  h14ed1c1_0            conda-forge/osx-arm64     Cached
  + libgrpc                            1.49.1  h55edf5b_1            conda-forge/osx-arm64     Cached
  + libiconv                             1.17  he4db4b2_0            conda-forge/osx-arm64     Cached
  + libkml                              1.3.0  h41464e4_1015         conda-forge/osx-arm64     Cached
  + liblapack                           3.9.0  16_osxarm64_openblas  conda-forge/osx-arm64     Cached
  + libnetcdf                           4.8.1  nompi_h2510be2_106    conda-forge/osx-arm64     Cached
  + libnghttp2                         1.47.0  h519802c_1            conda-forge/osx-arm64     Cached
  + libopenblas                        0.3.21  openmp_hc731615_3     conda-forge/osx-arm64     Cached
  + libpng                             1.6.38  h76d750c_0            conda-forge/osx-arm64     Cached
  + libpq                                14.5  h2af30dc_1            conda-forge/osx-arm64     Cached
  + libprotobuf                        3.21.9  hb5ab8b9_0            conda-forge/osx-arm64     Cached
  + librttopo                           1.1.0  h275bb25_11           conda-forge/osx-arm64     Cached
  + libspatialindex                     1.9.3  hbdafb3b_4            conda-forge/osx-arm64     Cached
  + libspatialite                       5.0.1  hca80f78_21           conda-forge/osx-arm64     Cached
  + libsqlite                          3.39.4  h76d750c_0            conda-forge/osx-arm64     Cached
  + libssh2                            1.10.0  h7a5bd25_3            conda-forge/osx-arm64     Cached
  + libtiff                             4.4.0  hfa0b094_4            conda-forge/osx-arm64     Cached
  + libwebp-base                        1.2.4  h57fd34a_0            conda-forge/osx-arm64     Cached
  + libxcb                               1.13  h9b22ae9_1004         conda-forge/osx-arm64     Cached
  + libxml2                            2.10.3  h87b0503_0            conda-forge/osx-arm64     Cached
  + libzip                              1.9.2  h76ab92c_1            conda-forge/osx-arm64     Cached
  + libzlib                            1.2.13  h03a7124_4            conda-forge/osx-arm64     Cached
  + llvm-openmp                        14.0.4  hd125106_0            conda-forge/osx-arm64     Cached
  + lz4-c                               1.9.3  hbdafb3b_1            conda-forge/osx-arm64     Cached
  + markdown                            3.4.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + markupsafe                          2.1.1  py310h8e9501a_2       conda-forge/osx-arm64     Cached
  + matplotlib-base                     3.6.2  py310h78c5c2f_0       conda-forge/osx-arm64     Cached
  + multidict                           6.0.2  py310h8e9501a_2       conda-forge/osx-arm64     Cached
  + munch                               2.5.0  py_0                  conda-forge/noarch        Cached
  + munkres                             1.1.4  pyh9f0ad1d_0          conda-forge/noarch        Cached
  + ncurses                               6.3  h07bb92c_1            conda-forge/osx-arm64     Cached
  + ninja                              1.11.0  hf86a087_0            conda-forge/osx-arm64     Cached
  + nspr                                 4.32  hbdafb3b_1            conda-forge/osx-arm64     Cached
  + nss                                  3.78  h1483a63_0            conda-forge/osx-arm64     Cached
  + numpy                              1.23.4  py310h5d7c261_1       conda-forge/osx-arm64     Cached
  + oauthlib                            3.2.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + omegaconf                           2.2.3  py310hbe9552e_0       conda-forge/osx-arm64     Cached
  + openjpeg                            2.5.0  h5d4e404_1            conda-forge/osx-arm64     Cached
  + openssl                             3.0.7  h03a7124_0            conda-forge/osx-arm64     Cached
  + packaging                            21.3  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pcre                                 8.45  hbdafb3b_0            conda-forge/osx-arm64     Cached
  + pcre2                               10.37  hcf5f1cc_1            conda-forge/osx-arm64     Cached
  + pillow                              9.2.0  py310h9337a76_3       conda-forge/osx-arm64     Cached
  + pip                                  22.3  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pixman                             0.40.0  h27ca646_0            conda-forge/osx-arm64     Cached
  + poppler                           22.11.0  hae7f5f0_0            conda-forge/osx-arm64     Cached
  + poppler-data                       0.4.11  hd8ed1ab_0            conda-forge/noarch        Cached
  + postgresql                           14.5  ha48369c_1            conda-forge/osx-arm64     Cached
  + pretrainedmodels                    0.7.4  pyhd8ed1ab_2          conda-forge/noarch        Cached
  + proj                                9.1.0  h3bdf472_0            conda-forge/osx-arm64     Cached
  + protobuf                           4.21.9  py310h0f1eb42_0       conda-forge/osx-arm64     Cached
  + pthread-stubs                         0.4  h27ca646_1001         conda-forge/osx-arm64     Cached
  + pyasn1                              0.4.8  py_0                  conda-forge/noarch        Cached
  + pyasn1-modules                      0.2.7  py_0                  conda-forge/noarch        Cached
  + pycparser                            2.21  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pydeprecate                         0.3.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyjwt                               2.6.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyopenssl                          22.1.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyparsing                           3.0.9  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyproj                              3.4.0  py310hce8d790_2       conda-forge/osx-arm64     Cached
  + pysocks                             1.7.1  pyha2e5f31_6          conda-forge/noarch        Cached
  + python                             3.10.6  hae75cb6_0_cpython    conda-forge/osx-arm64     Cached
  + python-dateutil                     2.8.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + python_abi                           3.10  2_cp310               conda-forge/osx-arm64     Cached
  + pytorch                            1.12.1  cpu_py310h7410233_1   conda-forge/osx-arm64     Cached
  + pytorch-lightning                   1.5.8  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyu2f                               0.1.5  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + pyyaml                                6.0  py310h8e9501a_5       conda-forge/osx-arm64     Cached
  + rasterio                            1.3.3  py310hbb0e019_2       conda-forge/osx-arm64     Cached
  + re2                            2022.06.01  h9a09cb3_0            conda-forge/osx-arm64     Cached
  + readline                            8.1.2  h46ed386_0            conda-forge/osx-arm64     Cached
  + requests                           2.28.1  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + requests-oauthlib                   1.3.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + rsa                                   4.9  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + rtree                               1.0.1  py310ha3239f5_1       conda-forge/osx-arm64     Cached
  + scikit-learn                        1.1.3  py310ha00a7cd_1       conda-forge/osx-arm64     Cached
  + scipy                               1.9.3  py310ha0d8a01_1       conda-forge/osx-arm64     Cached
  + segmentation-models-pytorch         0.3.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + setuptools                         65.5.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + shapely                             1.8.5  py310hc253cc3_1       conda-forge/osx-arm64     Cached
  + six                                1.16.0  pyh6c4a22f_0          conda-forge/noarch        Cached
  + sleef                               3.5.1  h156473d_2            conda-forge/osx-arm64     Cached
  + snappy                              1.1.9  h17c5cce_2            conda-forge/osx-arm64     Cached
  + snuggs                              1.4.7  py_0                  conda-forge/noarch        Cached
  + sqlite                             3.39.4  h2229b38_0            conda-forge/osx-arm64     Cached
  + tensorboard                         2.4.1  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + tensorboard-plugin-wit              1.8.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + threadpoolctl                       3.1.0  pyh8a188c0_0          conda-forge/noarch        Cached
  + tiledb                             2.11.3  h9bd36d0_1            conda-forge/osx-arm64     Cached
  + timm                               0.4.12  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + tk                                 8.6.12  he1e0b03_0            conda-forge/osx-arm64     Cached
  + torchgeo                            0.3.1  pyhd8ed1ab_1          conda-forge/noarch        Cached
  + torchmetrics                        0.9.3  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + torchvision                        0.13.0  cpu_py310he68663e_0   conda-forge/osx-arm64     Cached
  + tqdm                               4.64.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + typing-extensions                   4.4.0  hd8ed1ab_0            conda-forge/noarch        Cached
  + typing_extensions                   4.4.0  pyha770c72_0          conda-forge/noarch        Cached
  + tzcode                              2022e  h1a8c8d9_0            conda-forge/osx-arm64     Cached
  + tzdata                              2022f  h191b570_0            conda-forge/noarch        Cached
  + unicodedata2                       15.0.0  py310h8e9501a_0       conda-forge/osx-arm64     Cached
  + urllib3                           1.26.11  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + werkzeug                            2.2.2  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + wheel                              0.37.1  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + xerces-c                            3.2.4  h627aa08_1            conda-forge/osx-arm64     Cached
  + xorg-libxau                         1.0.9  h27ca646_0            conda-forge/osx-arm64     Cached
  + xorg-libxdmcp                       1.1.3  h27ca646_0            conda-forge/osx-arm64     Cached
  + xz                                  5.2.6  h57fd34a_0            conda-forge/osx-arm64     Cached
  + yaml                                0.2.5  h3422bc3_2            conda-forge/osx-arm64     Cached
  + yarl                                1.8.1  py310h8e9501a_0       conda-forge/osx-arm64     Cached
  + zipp                               3.10.0  pyhd8ed1ab_0          conda-forge/noarch        Cached
  + zlib                               1.2.13  h03a7124_4            conda-forge/osx-arm64     Cached
  + zstd                                1.5.2  h8128057_4            conda-forge/osx-arm64     Cached

  Summary:

  Install: 197 packages

  Total download: 0 B

───────────────────────────────────────────────────────────────────────────────────────────────────────

Confirm changes: [Y/n] y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ mamba activate torchgeo

To deactivate an active environment, use

     $ mamba deactivate
```

### Steps to reproduce

``` 

❯ conda create -n torchgeo python pip 'torchgeo[datasets]' -c conda-forge
❯ conda activate torchgeo
❯ python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchgeo
>>> torchgeo.__version__
'0.3.1'
>>> from torchgeo.datamodules import TropicalCycloneDataModule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'TropicalCycloneDataModule' from 'torchgeo.datamodules' (/Users/calkoen/miniconda3/envs/torchgeo/lib/python3.10/site-packages/torchgeo/datamodules/__init__.py)
```

### Version

0.3.1

**Comment by FlorisCalkoen** [comment]
When installing the latest build it works: 

```
conda activate torchgeo
pip3 install git+https://github.com/microsoft/torchgeo.git
pip3 install 'torchgeo[datasets]'  ## just to be sure
python
# Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ] on darwin
# Type "help", "copyright", "credits" or "license" for more information.
>>> import torchgeo
>>> torchgeo.__version__
'0.4.0.dev0'
>>> from torchgeo.datamodules import TropicalCycloneDataModule
>>> TropicalCycloneDataModule()
<torchgeo.datamodules.TropicalCycloneDataModule object at 0x1010234c0>
```

**Comment by isaaccorley** [comment]
Your link for the trainer tutorial was for the latest docs. You can find the stable docs [here](https://torchgeo.readthedocs.io/en/stable/tutorials/trainers.html).  `TropicalCycloneDatamodule` was recently renamed from `CycloneDataModule` but we haven't had a release including this change yet.
